### ISSUE TITLE
Options to change sync offset & adjust stroke length not displaying under "File Info" within an Interactive Scene

### ISSUE THREAD

**Issue by mdoh66** [blackx69/StashInteractiveTools#1]
Plug-in is installed, and the Plug-in options and tasks show up, but not the option to adjust the sync offset or the stroke length.

When trying to run the "init" task within Plugin Tasks, the following error shows up in the logs:

2024-12-19 13:58:57Error   Plugin returned error: exit status 1
2024-12-19 13:58:57Error   [Plugin / Stash Interactive Tools] KeyError: 'scene_id'
2024-12-19 13:58:57Error   [Plugin / Stash Interactive Tools]                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
2024-12-19 13:58:57Error   [Plugin / Stash Interactive Tools]     scene_id = FRAGMENT["args"]['scene_id']
2024-12-19 13:58:57Error   [Plugin / Stash Interactive Tools]   File "/root/.stash/plugins/StashInteractiveTools/StashInteractiveTools.py", line 90, in analyze_scene
2024-12-19 13:58:57Error   [Plugin / Stash Interactive Tools]               ^^^^^^^^^^^^^^^
2024-12-19 13:58:57Error   [Plugin / Stash Interactive Tools]     scripts = analyze_scene()
2024-12-19 13:58:57Error   [Plugin / Stash Interactive Tools]   File "/root/.stash/plugins/StashInteractiveTools/StashInteractiveTools.py", line 153, in main
2024-12-19 13:58:57Error   [Plugin / Stash Interactive Tools]     main()
2024-12-19 13:58:57Error   [Plugin / Stash Interactive Tools]   File "/root/.stash/plugins/StashInteractiveTools/StashInteractiveTools.py", line 162, in <module>
2024-12-19 13:58:57Error   [Plugin / Stash Interactive Tools] Traceback (most recent call last):

**Comment by blackx69** [comment]
This has been fixed in the `develop` branch, look out for upcoming update
